apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  tls:
    - hosts:
        - argocd.ryuzu.dev
      secretName: ryuzu-dev-tls-secret
  rules:
    - host: argocd.ryuzu.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: argocd-server
                port:
                  number: 80