apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloudflare-ingress-controller-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/Y-RyuZU/CloudflareIngressController.git'
        revision: HEAD
        directories:
          - path: overlays/*
    - git:
        repoURL: 'https://github.com/Y-RyuZU/CloudflareIngressController.git'
        revision: HEAD
        files:
          - path: applicationset-cloudflare.yaml
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        app.kubernetes.io/managed-by: argocd
    spec:
      project: default
      source:
        repoURL: 'https://github.com/Y-RyuZU/CloudflareIngressController.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m