apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  tls:
    - hosts:
        - ryuzu.dev
      secretName: ryuzu-dev-tls-secret
  rules:
    - host: ryuzu.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ryuzu-portfolio-service
                port:
                  number: 3000