apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  tls:
    - hosts:
        - dashboard.k8s.ryuzu.dev
      secretName: ryuzu-dev-tls-secret
  rules:
    - host: dashboard.k8s.ryuzu.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 443