apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubenetes.io/backend-protocol: "HTTPS"
spec:
  tls:
    - hosts:
        - kubedash.k8s.ryuzu.dev
      secretName: ryuzu-dev-tls-secret
  rules:
    - host: kubedash.ryuzu.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: kubernetes-dashboard
                port:
                  number: 443