apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-applications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Y-RyuZU/CloudflareIngressController.git'
    targetRevision: HEAD
    path: argocd/applicationset-cloudflare.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true