apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubenetes.io/backend-protocol: "HTTP"
    kubernetes.io/ingress.class: "cloudflare-tunnel"
spec:
  ingressClassName: cloudflare-tunnel
  rules: []